src/Entity/Rendezvous.php
<?php

namespace App\Entity;

use App\Repository\RendezvousRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=RendezvousRepository::class)
 */
class Rendezvous
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $service;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTime")
     * @var string A "Y-m-d H:i:s"
     * @Assert\GreaterThan("today")
     */
    private $date_rendezvous;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $description_rendezvous;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 8,
     *      max = 8,
     *      minMessage = "le numero est invalide verifer la longeur",
     *      maxMessage = "le numero est invalide verifer la longeur"
     * )
     */
    private $telephonenum;

    /**
     * @ORM\OneToOne(targetEntity=Avis::class, inversedBy="rendezvous")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $avis;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $adressrend;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getService(): ?string
    {
        return $this->service;
    }

    public function setService(string $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function getDateRendezvous(): ?\DateTimeInterface
    {
        return $this->date_rendezvous;
    }

    public function setDateRendezvous(\DateTimeInterface $date_rendezvous): self
    {
        $this->date_rendezvous = $date_rendezvous;

        return $this;
    }

    public function getDescriptionRendezvous(): ?string
    {
        return $this->description_rendezvous;
    }

    public function setDescriptionRendezvous(string $description_rendezvous): self
    {
        $this->description_rendezvous = $description_rendezvous;

        return $this;
    }

    public function getTelephonenum(): ?string
    {
        return $this->telephonenum;
    }

    public function setTelephonenum(string $telephonenum): self
    {
        $this->telephonenum = $telephonenum;

        return $this;
    }

    public function getAvis(): ?Avis
    {
        return $this->avis;
    }

    public function setAvis(Avis $avis): self
    {
        $this->avis = $avis;

        return $this;
    }

    public function getAdressrend(): ?string
    {
        return $this->adressrend;
    }

    public function setAdressrend(string $adressrend): self
    {
        $this->adressrend = $adressrend;

        return $this;
    }

    public function getClient(): ?user
    {
        return $this->client;
    }

    public function setClient(?user $client): self
    {
        $this->client = $client;

        return $this;
    }

}

src/Form/RendezvousType.php
<?php

namespace App\Form;

use App\Entity\Rendezvous;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class RendezvousType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('service', ChoiceType::class, array(
                'choices'=> array(
                    'Reparation'=> 'Reparation',
                    'Installation' => 'Installation',
                ),
            ))
            ->add('date_rendezvous',DateTimeType::class, [
                'placeholder' => [
                    'année' => 'Année', 'mois' => 'Mois', 'jour' => 'Jour',
                    'heure' => 'Heure', 'minute' => 'Minute', 'seconde' => 'Seconde',
                ],
            ])
            ->add('description_rendezvous' )
            ->add('adressrend')

            ->add('telephonenum')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Rendezvous::class,
        ]);
    }
}

src/Controller/RendezvousController.php
<?php

namespace App\Controller;

use App\Entity\Avis;

use App\Entity\Recherche;
use App\Entity\Rendezvous;
use App\Entity\User;
use App\Form\AvisType;
use App\Form\RendezvousType;
use App\Repository\AvisRepository;
use App\Repository\RendezvousRepository;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\Routing\Annotation\Route;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;
use Knp\Component\Pager\PaginatorInterface;
// Include Dompdf required namespaces
use Dompdf\Dompdf;
use Dompdf\Options;


class RendezvousController extends AbstractController
{
    /**
     * @Route("/rendezvous/Afficheback", name="rendezvous_back", methods={"GET"})
     */

    public function AfficheBack(RendezvousRepository $rendezvousRepository,Request $request): Response
    {
        $em = $this->getDoctrine()->getManager();

        $query = $em->createQuery(
            'DELETE  FROM App\Entity\Rendezvous n
             WHERE n.date_rendezvous < CURRENT_TIMESTAMP()'
        );

        $rendezvous = $query->getResult();


        return $this->render('rendezvous/AfficheBack.html.twig',
            array('rendezvous' => $rendezvousRepository->findAll()));


    }

    /**
     * @Route("/rendezvous/stats", name="statRendezvous")
     */
    public function stat()
    {
        $repository = $this->getDoctrine()->getRepository(Rendezvous::class);
        $rendezvous = $repository->findAll();

        $em = $this->getDoctrine()->getManager();

        $r1=0;
        $r2=0;

        foreach ($rendezvous as $rendezvou)
        {
            if ( $rendezvou->getService()=="Reparation")  :

                $r1+=1;
            else:

                $r2+=1;


            endif;

        }

        $pieChart = new PieChart();
        $pieChart->getData()->setArrayToDataTable(
            [['Service', 'nombre'],
                ['Reparation', $r1],
                ['Installation', $r2],
            ]
        );
        $pieChart->getOptions()->setTitle('Services Le plus demandé ');
        $pieChart->getOptions()->setHeight(500);
        $pieChart->getOptions()->setWidth(900);
        $pieChart->getOptions()->getTitleTextStyle()->setBold(true);
        $pieChart->getOptions()->getTitleTextStyle()->setColor('#FFFFFF');
        $pieChart->getOptions()->getTitleTextStyle()->setItalic(true);
        $pieChart->getOptions()->getTitleTextStyle()->setFontName('Arial');
        $pieChart->getOptions()->getTitleTextStyle()->setFontSize(20);
        $pieChart->getOptions()->setBackgroundColor('#454d55');


        return $this->render('rendezvous/stat.html.twig', array('piechart' => $pieChart));
    }

    /**
     * @Route("/rendezvous/tri", name="trirdv")
     */
    public function Tri(Request $request)
    {
        $em = $this->getDoctrine()->getManager();


        $query = $em->createQuery(
            'SELECT n FROM App\Entity\Rendezvous n
            ORDER BY n.service Desc, n.telephonenum  , n.client'
        );

        $rendezvous = $query->getResult();



        return $this->render('rendezvous/AfficheBack.html.twig',
            array('rendezvous' => $rendezvous));

    }

    /**
     * @Route("/rendezvous/tri2", name="trirdv2")
     */
    public function Tri2(Request $request)
    {
        $em = $this->getDoctrine()->getManager();


        $query = $em->createQuery(
            'SELECT n FROM App\Entity\Rendezvous n
            ORDER BY n.id'
        );

        $rendezvous = $query->getResult();



        return $this->render('rendezvous/AfficheBack.html.twig',
            array('rendezvous' => $rendezvous));

    }

    /**
     * @Route("/rendezvous", name="rendezvous_index", methods={"GET","POST"})
     */

    public function index(RendezvousRepository $rendezvousRepository, PaginatorInterface $paginator, Request $request): Response

    {
        $rendezvous=new Recherche();
        $form=$this->createFormBuilder($rendezvous)
            ->add('titre',TextType::class,array('attr'=>array('class'=>'form')))
            ->getForm();

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $term=$rendezvous->getTitre();
            $allrendezvous = $rendezvousRepository->search($term);
        }
        else
        {
            $allrendezvous = $rendezvousRepository->findAll();
        }
        $rendezvousRepository= $paginator->paginate(
            $allrendezvous,
            $request->query->getInt('page',1),
            5
        );
        return $this->render('rendezvous/index.html.twig', [
            'rendezvouses' => $rendezvousRepository,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/rendezvous/calendar", name="rendezvous_calendar")
     */
    public function rendezvous(RendezvousRepository $rendezvousRepository)
    {
        $user = $this->getUser();
        $rendezvous=$rendezvousRepository->rdvs($user);
        $rdvs = [];


        foreach($rendezvous as $rendezvou){

            $rdvs[] = [
                'id' => $rendezvou->getId(),
                'title'=>$rendezvou->getTitre(),
                'titre' => $rendezvou->getTitre(),
                'service' => $rendezvou->getService(),
                'start' => $rendezvou->getDateRendezvous()->format('Y-m-d H:i:s'),
                'description_rendezvous' => $rendezvou->getDescriptionRendezvous(),
                'adressrend' => $rendezvou->getAdressrend(),
                'telephonenum' => $rendezvou->getTelephonenum(),

            ];
        }

        $data = json_encode($rdvs);

        return $this->render('rendezvous/calendar.html.twig', compact('data'));
    }

    /**
     * @Route("/rendezvous/new", name="rendezvous_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $rendezvou = new Rendezvous();
        $rendezvou->setClient($this->getUser());
        $form = $this->createForm(RendezvousType::class, $rendezvou);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($rendezvou);
            $entityManager->flush();

            return $this->redirectToRoute('rendezvous_index', [], Response::HTTP_SEE_OTHER);

        }

        return $this->render('rendezvous/new.html.twig', [
            'rendezvou' => $rendezvou,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/rendezvous/{id}", name="rendezvous_show", methods={"GET"})
     */
    public function show(Rendezvous $rendezvou): Response
    {
        return $this->render('rendezvous/show.html.twig', [
            'rendezvou' => $rendezvou,
        ]);
    }


    /**
     * @Route("/rendezvous/{id}/show1", name="monrendezvous_show1", methods={"GET"})
     */
    public function show1(Rendezvous $rendezvou): Response
    {$pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);

        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('rendezvous/monrdv.html.twig', [
            'rendezvou' => $rendezvou,
        ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A6', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (inline view)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => true
        ]);
        return $this->redirectToRoute("rendezvous_show");
    }

    /**
     * @Route("/rendezvous/{id}/edit", name="rendezvous_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Rendezvous $rendezvou, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RendezvousType::class, $rendezvou);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('rendezvous_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('rendezvous/edit.html.twig', [
            'rendezvou' => $rendezvou,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/rendezvous/{id}", name="rendezvous_delete", methods={"POST"})
     */
    public function delete(Request $request, Rendezvous $rendezvou, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rendezvou->getId(), $request->request->get('_token'))) {
            $entityManager->remove($rendezvou);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rendezvous_index', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route("/Rendezvous/excel", name="excel", methods={"GET"})
     */
    public function excel()
    {
        $spreadsheet = new Spreadsheet();

        /* @var $sheet \PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet */
        // on définie les en têtes de nos enregistrements
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setCellValue('A1','ID')
            ->setCellValue('B1','Titre')
            ->setCellValue('C1','Service')
            ->setCellValue('D1','Date du rendez-vous')
            ->setCellValue('E1','Description du rendez-vous')
            ->setCellValue('F1','Numero de telephone ')
            ->setCellValue('G1','Adresse due Rendez-vous ')

templates/rendezvous/AfficheBack.html.twig
{% extends 'baseback.html.twig' %}
{% block title %} Espace Admin {% endblock %}
{% block titre1 %} Voir Les Rendez Vous {% endblock %}
{% block content %}
    <h1>Liste des Rendez-vous</h1>
    <table class="table" align="center">
        <thead>
        <tr>

            <th>Titre</th>
            <th>Service</th>
            <th>Date_rendezvous</th>
            <th>Description_rendezvous</th>
            <th>Telephonenum</th>
            <th>Adresse</th>
            <th>Client_id</th>

        </tr>
        </thead>
        <tbody>
        {% for rendezvou in rendezvous %}
            <tr>

                <td>{{ rendezvou.titre }}</td>
                <td>{{ rendezvou.service }}</td>
                <td>{{ rendezvou.dateRendezvous ? rendezvou.dateRendezvous|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ rendezvou.descriptionRendezvous }}</td>
                <td>{{ rendezvou.telephonenum }}</td>
                <td>{{ rendezvou.adressrend }}</td>
                <td>{{ rendezvou.client.id }}</td>

            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="card-body">

        <a class="btn btn-primary" href="{{path('trirdv')}}">Tri par Services ,n°tél et id-clients  </a>
        <a class="btn btn-primary" href="{{path('trirdv2')}}">Tri par Date d'insèrtions</a>
        <a class="btn btn-primary" href="{{path('excel')}}">excel</a>

        <a class="btn btn-primary" href="{{path('statRendezvous')}}">Stat par type de Service</a>

    </div>
{% endblock %}

templates/rendezvous/_delete_form.html.twig
<form method="post" action="{{ path('rendezvous_delete', {'id': rendezvou.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rendezvou.id) }}">
    <button  class="btn btn-warning " >Supprimer</button>
</form>

templates/rendezvous/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}

<table id="rendezvous" width="450px">

    <tr>
        <td>{{form_label(form.titre,"Titre: ")  }}</td>
        <td>{{ form_widget(form.titre)}}</td>
        <td id='info'>{{ form_errors(form.titre)}}</td>
    </tr>

    <tr>
        <td>{{form_label(form.service,"Services: ")  }}</td>
        <td>{{ form_widget(form.service)}}</td>
        <td id='info'>{{ form_errors(form.service)}}</td>
    </tr>
    <tr>
        <td>{{form_label(form.date_rendezvous,"Date Rendez-Vous: "  )  }}</td>
        <td>{{ form_widget(form.date_rendezvous)}}</td>
    </tr>

    <tr>
        <td>{{form_label(form.description_rendezvous,"Descriptions: ")  }}</td>
        <td>{{ form_widget(form.description_rendezvous)}}</td>

    </tr>
    <tr>
        <td>{{form_label(form.telephonenum,"Tèl: ")  }}</td>
        <td>{{ form_widget(form.telephonenum)}}</td>
        <td id='info'>{{ form_errors(form.telephonenum)}}</td>
    </tr>
    <tr>
        <td>{{form_label(form.adressrend,"Adresse: ")  }}</td>
        <td>{{ form_widget(form.adressrend)}}</td>
    </tr>

</table>


{{ form_widget(form) }}
<br>
<button class="btn btn-warning "  > {{ button_label|default('Enregistrer') }}</button>

{{ form_end(form) }}

templates/rendezvous/calendar.html.twig
{% extends 'base.html.twig' %}
{% block title %} Chritech {% endblock %}
{% block bg%} {{ asset('front/assets/img/rdvbg.png') }}  {% endblock %}
{% block titre1 %}Services{% endblock %}
{% block titre2 %} <a href="{{ path('rendezvous_index') }}" style="color: antiquewhite">Rendez-vous <h6 style="color: floralwhite" ><small>CLiquez ici pour revinr à la liste</small></h6></a>
{% endblock %}
{% block content %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.3.0/main.min.css" integrity="sha256-uq9PNlMzB+1h01Ij9cx7zeE2OR2pLAfRw3uUUOOPKdA=" crossorigin="anonymous">

    <style>
        #calendrier{
            width: 80%;
            margin: auto;
        }
    </style>
        <div id="calendrier">

        </div>


    <script>
        window.onload = () => {
            let calendarElt = document.querySelector("#calendrier")

            let calendar = new FullCalendar.Calendar(calendarElt, {
                initialView: 'dayGridMonth',
                locale: 'fr',
                timeZone: 'Europe/Paris',
                headerToolbar: {
                    start: 'prev,next today',
                    center: 'title',
                    end: 'dayGridMonth,timeGridWeek'
                },
                events: {{ data|raw }},
                editable: true,
                eventResizableFromStart: true

            })
            calendar.on('eventChange', (e) => {
                let url = `/api/${e.event.id}/edit`
                let donnees = {
                    "titre": e.event.extendedProps.titre,
                    "service": e.event.extendedProps.service,
                    "start": e.event.start,
                    "description_rendezvous": e.event.extendedProps.description_rendezvous,
                    "adressrend": e.event.extendedProps.adressrend,
                    "telephonenum": e.event.extendedProps.telephonenum

                }
                let xhr = new XMLHttpRequest
                xhr.open("PUT", url)
                xhr.send(JSON.stringify(donnees))
            })

            calendar.render()
        }


    </script>
        <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.3.0/main.min.js" integrity="sha256-DBxkGZLxKsLKhz054qUpBqtotG00r9AELGpSigJujLg=" crossorigin="anonymous"></script>


{% endblock %}

templates/rendezvous/index.html.twig
{% extends 'base.html.twig' %}
{% block title %} Chritech {% endblock %}
{% block bg%} {{ asset('front/assets/img/rdvbg.png') }}  {% endblock %}
{% block titre1 %}Services{% endblock %}
{% block titre2 %} <a href="{{ path('rendezvous_new') }}  " style="color: antiquewhite">Rendez-vous <h6 style="color: floralwhite" ><small>Pour prendre un Rendez-vous Cliquer ici</small></h6></a>

{% endblock %}


{% block content %}


    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Event Calendar</title>
        <style>.event-container {
                font-family: "Roboto", sans-serif;
                max-width: 800px;
                margin: 0 auto;
            }

            .event-container h3.year {
                font-size: 40px;
                text-align: center;
                border-bottom: 1px solid #b1b1b1;
            }

            .event-container .event {
                box-shadow: 0 4px 16px -8px rgba(0, 0, 0, 0.4);
                display: flex;
                border-radius: 8px;
                margin: 32px 0;
            }

            .event .event-left {
                background: #222;
                min-width: 82px;
                display: flex;
                align-items: center;
                justify-content: center;
                color: #eee;
                padding: 8px 48px;
                font-weight: bold;
                text-align: center;
                border-radius: 8px 0 0 8px;
            }

            .event .event-left .date {
                font-size: 56px;
            }

            .event .event-left .month {
                font-size: 16px;
                font-weight: normal;
            }

            .event .event-right {
                display: flex;
                flex-direction: column;
                justify-content: center;
                padding: 0 24px;
            }

            .event .event-right h3.event-title {
                font-size: 24px;
                margin: 24px 0 10px 0;
                color: #218bbb;
                text-transform: uppercase;
            }

            .event .event-right .event-timing {
                background: #fff8ba;
                display: flex;
                align-items: center;
                justify-content: center;
                width: 100px;
                padding: 8px;
                border-radius: 16px;
                margin: 24px 0;
                font-size: 14px;
            }

            .event .event-right .event-timing img {
                height: 20px;
                padding-right: 8px;
            }

            @media (max-width: 550px) {
                .event {
                    flex-direction: column;
                }

                .event .event-left {
                    padding: 0;
                    border-radius: 8px 8px 0 0;
                }

                .event .event-left .event-date .date,
                .event .event-left .event-date .month {
                    display: inline-block;
                    font-size: 24px;
                }

                .event .event-left .event-date {
                    padding: 10px 0;
                }
                .center {
                    padding: 70px 0;
                    border: 3px solid green;
                }
            }
        </style>
    </head>
    <body>


    <div class="event-container">

            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button class="btn btn-dark">{{ button_label|default('rechercher') }}</button>
        <a class="btn btn-dark" href="{{ path('rendezvous_calendar') }}"> Calendrier</a>

        {{ form_end(form) }}


                    {% for rendezvou in rendezvouses %}
{% if rendezvou.client.id==app.user.id %}

            <div class="event">
                <div class="event-left">
                    <div class="event-date">
                        <div class="date">{{ rendezvou.dateRendezvous ? rendezvou.dateRendezvous|date('d') : '' }}
                        </div>
                        <div class="month">{{ rendezvou.dateRendezvous ? rendezvou.dateRendezvous|date('Y-m') : '' }}
                        </div>
                    </div>
                </div>

                <div class="event-right">
                    <h3 class="event-title" onclick="window.location.href = '{{ path('rendezvous_show', {'id': rendezvou.id}) }}';">{{ rendezvou.titre }}</h3>

                    <div class="event-description">
                        {{ rendezvou.descriptionRendezvous }}
                    </div>

                   <span>

                       <a class="event-timing"> <img src="{{ asset('front/assets/img/time.png') }}" alt=""/>{{ rendezvou.dateRendezvous ? rendezvou.dateRendezvous|date('H:i:s') : '' }}</a>

            <p align="center">
                        <a class="btn btn-dark" href="{{ path('rendezvous_edit', {'id': rendezvou.id}) }}">Modifier mon Rendez-vous</a>

                        <a class="btn btn-dark"  href="{{ path('avis_new', {'rendezvous': rendezvou.id}) }}">Ajouter un Avis</a>
                  {% if rendezvou.avis is not null %}
                               <a class="btn btn-dark" href="{{ path('avis_show', {'id': rendezvou.avis.id}) }}">Consulter mon Avis</a>
                           {% endif %}
                       </p>
                    </span>

                </div>
            </div>
{% endif %}
        {% endfor %}
        {{ knp_pagination_render(rendezvouses) }}

    </div>
    </body>

{% endblock %}

templates/rendezvous/monrdv.html.twig
{% block content %}
    <h1 align="center">Mon rendez-vous</h1>
<br>
    <table class="table" align="center" >
        <tbody>

        <tr>
            <th>Titre  :  </th>
            <td>{{ rendezvou.titre }}</td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <th>Services demandé : </th>
            <td>{{ rendezvou.service }}</td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <th>Date du rendez-vous : </th>
            <td>{{ rendezvou.dateRendezvous ? rendezvou.dateRendezvous|date('Y-m-d') : '' }}</td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <th>Description : </th>
            <td>{{ rendezvou.descriptionRendezvous }}</td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <th>Adresse : </th>
            <td>{{ rendezvou.adressrend }}</td>
        </tr>
        <tr><td></td></tr>
        <tr>
            <th>Numéro de téléphone :  </th>
            <td>{{ rendezvou.telephonenum }}</td>
        </tr>
        </tbody>
    </table>


{% endblock %}

templates/rendezvous/show.html.twig
{% extends 'base.html.twig' %}


{% block title %} Chritech {% endblock %}
{% block bg%} {{ asset('front/assets/img/rdvbg.png') }}  {% endblock %}
{% block titre1 %}Services{% endblock %}
{% block titre2 %} <a  style="color: antiquewhite">Rendez-vous<h6 style="color: floralwhite" ><small>Voici Votre Rendez-vous </small></h6></a>

{% endblock %}

{% block content %}

    <table class="table">
        <tbody>

            <tr>
                <th>Titre</th>
                <td>{{ rendezvou.titre }}</td>
            </tr>
            <tr>
                <th>Service</th>
                <td>{{ rendezvou.service }}</td>
            </tr>
            <tr>
                <th>Date_rendezvous</th>
                <td>{{ rendezvou.dateRendezvous ? rendezvou.dateRendezvous|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Description_rendezvous</th>
                <td>{{ rendezvou.descriptionRendezvous }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ rendezvou.adressrend }}</td>
            </tr>
            <tr>
                <th>Telephonenum</th>
                <td>{{ rendezvou.telephonenum }}</td>
            </tr>
        </tbody>
    </table>
  <p align="center"> <a href="{{ path('rendezvous_index') }}">Retourner   </a>
    <a href="{{ path('monrendezvous_show1', {'id': rendezvou.id}) }}">PDF</a>
    <div align="center" >{{ include('rendezvous/_delete_form.html.twig') }} </div></p>


{% endblock %}