src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $utilisateur;

    /**
     * @ORM\Column(type="text")
     */
    private $contenue;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_heure;

    /**
     * @ORM\ManyToOne(targetEntity=Blog::class, inversedBy="commentaires")
     */
    private $blog_id;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="commentaires")
     */
    private $article_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUtilisateur(): ?string
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(string $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getContenue(): ?string
    {
        return $this->contenue;
    }

    public function setContenue(string $contenue): self
    {
        $this->contenue = $contenue;

        return $this;
    }

    public function getDateHeure(): ?\DateTimeInterface
    {
        return $this->date_heure;
    }

    public function setDateHeure(\DateTimeInterface $date_heure): self
    {
        $this->date_heure = $date_heure;

        return $this;
    }

    public function getBlogId(): ?Blog
    {
        return $this->blog_id;
    }

    public function setBlogId(?Blog $blog_id): self
    {
        $this->blog_id = $blog_id;

        return $this;
    }

    public function getArticleId(): ?Article
    {
        return $this->article_id;
    }

    public function setArticleId(?Article $article_id): self
    {
        $this->article_id = $article_id;

        return $this;
    }

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->date_heure = new \DateTime('now');
    }
}

src/Form/CommentaireType.php
<?php

namespace App\Form;

use App\Entity\Commentaire;
use Doctrine\DBAL\Types\DateTimeType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('contenue', TextareaType::class ,[
                'attr' => [
                    'placeholder'=> 'Exprimez-vous...'
                ]

            ])


        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commentaire::class,
        ]);
    }
}

src/Controller/CommentaireController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\CommentaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/commentaire")
 */
class CommentaireController extends AbstractController
{
    /**
     * @Route("/", name="commentaire_index", methods={"GET"})
     */
    public function index(CommentaireRepository $commentaireRepository): Response
    {
        return $this->render('commentaire/index.html.twig', [
            'commentaires' => $commentaireRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="commentaire_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($commentaire);
            $entityManager->flush();

            return $this->redirectToRoute('commentaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commentaire/new.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commentaire_show", methods={"GET"})
     */
    public function show(Commentaire $commentaire): Response
    {
        return $this->render('commentaire/show.html.twig', [
            'commentaire' => $commentaire,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="commentaire_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Commentaire $commentaire, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('commentaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commentaire/edit.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commentaire_delete", methods={"POST"})
     */
    public function delete(Request $request, Commentaire $commentaire, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentaire->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commentaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('commentaire_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commentaire/_delete_form.html.twig
<form method="post" action="{{ path('commentaire_delete', {'id': commentaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commentaire/_form.html.twig
{% block content %}



    <div class="container mt-5">
        <div class="form-group">
            <div class="form-label mt-4"></div>
            {{ form_start(form) }}
            {{ form_widget(form) }}
            <br>
            <button class="btn">{{ button_label|default('Save') }}</button>
            {{ form_end(form) }}

        </div>
    </div>


{% endblock %}

templates/commentaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commentaire{% endblock %}

{% block body %}
    <h1>Edit Commentaire</h1>

    {{ include('commentaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('commentaire_index') }}">back to list</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}

templates/commentaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire index{% endblock %}

{% block body %}
    <h1>Commentaire index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Utilisateur</th>
                <th>Contenue</th>
                <th>Date_heure</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commentaire in commentaires %}
            <tr>
                <td>{{ commentaire.id }}</td>
                <td>{{ commentaire.utilisateur }}</td>
                <td>{{ commentaire.contenue }}</td>
                <td>{{ commentaire.dateHeure ? commentaire.dateHeure|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('commentaire_show', {'id': commentaire.id}) }}">show</a>
                    <a href="{{ path('commentaire_edit', {'id': commentaire.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('commentaire_new') }}">Create new</a>
{% endblock %}

templates/commentaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commentaire{% endblock %}

{% block content %}
    <h1>Create new Commentaire</h1>

    {{ include('commentaire/_form.html.twig') }}

    <a href="{{ path('commentaire_index') }}">back to list</a>
{% endblock %}

templates/commentaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire{% endblock %}

{% block body %}
    <h1>Commentaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commentaire.id }}</td>
            </tr>
            <tr>
                <th>Utilisateur</th>
                <td>{{ commentaire.utilisateur }}</td>
            </tr>
            <tr>
                <th>Contenue</th>
                <td>{{ commentaire.contenue }}</td>
            </tr>
            <tr>
                <th>Date_heure</th>
                <td>{{ commentaire.dateHeure ? commentaire.dateHeure|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('commentaire_index') }}">back to list</a>

    <a href="{{ path('commentaire_edit', {'id': commentaire.id}) }}">edit</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}